name: Build and Push to GHCR

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read
  packages: write

jobs:
  build-arm:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        architecture: [arm64]

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional, for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ide
          file: ./ide/Dockerfile  # Path to Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/flleonx/ide:arm-${{ github.run_id }}
          platforms: linux/${{ matrix.architecture }}

  build-amd:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [amd64]

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (optional, for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ide
          file: ./ide/Dockerfile  # Path to Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/flleonx/ide:amd-${{ github.run_id }}
          platforms: linux/${{ matrix.architecture }}

  merge-and-push:
      needs: [build-amd, build-arm]
      runs-on: ubuntu-latest
      steps:
        - name: Log in to GHCR
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Create and push multi-architecture image
          run: |
            docker buildx imagetools create \
              --tag ghcr.io/flleonx/ide:latest \
              ghcr.io/flleonx/ide:amd-${{ github.run_id }} \
              ghcr.io/flleonx/ide:arm-${{ github.run_id }}
